### PR TITLE
Recipes

### PR DESCRIPTION
**Pull request by thijs-jung-trv**
The `recipes` package will handle all interactions with the Recipe Database and provides a generic Recipe class.

# Recipes
## Class
The Recipe class takes in a dictionary containing a source (str, e.g. "booking"), a prefix (str, e.g. "amenities"), field (map, e.g. `{"facility": "pool", "attribute": "available", "datatype": "boolean"}`), options (map, e.g. `{"value": "sun facing pool"}`).

The source and prefix become an attribute on the class, as well as every field in `options`. You can use it as follows:
```python
base_recipe = {
    'source': 'booking',
    'field': {
        'facility': 'pool',
        'attribute': 'cost',
         'datatype': 'cost'
     },
    'options': {
        'currency_regex': 'EUR',
        'amount_regex': 2.50,
        'rate_regex': 'per day',
    },
    'prefix': 'amenities'
}
```

```ipython
[1] from recipes import Recipe

[2] recipe = Recipe.from_dict(base_recipe)

[3] In: recipe.currency_regex == 2.50
[3] Out: True

[4] In: recipe.amount_regex
[4] Out: 2.50
```

## In Dynamodb
Recipes will be stored in Dynamodb with a primary key consisting of a Partition Key (source) and a sort key (a uuid). The Database method `put_recipe` receives a Recipe object, generates a uuid and stores the recipe. `get_recipe(source)` delivers a list of Recipe objects for that source.

# Tests
Tests have been written, but the percentage of mocks seems to be on the high side. Your recommendations are very welcome.

### CODE REVIEW

**Comment by gumuz** [comment]
@thijs-jung-trv I see the put_recipe also accepts a dict. In what cases will there be a dict instead of a recipe?

I'd suggest it *only* accepts recipes, unless there's a good reason

**Comment by thijs-jung-trv** [comment]
@gumuz Good point, coming to think of it, I don't really see why we would accept a dictionary. It seems cleaner to force anybody who wants to put recipes to actually use the Recipe class.

**Comment by gumuz** [comment]
I see a bunch of comments in the cloudformation template, please remove them :)

We can always find them in git if we need to

**Comment by thijs-jung-trv** [comment]
@gumuz Done!

**Pull request merged**
