### PR TITLE
Updates to cloudformation template to reflect changes in DBs

### PR DESCRIPTION
**Pull request by thijs-jung-trv**
I updated the cloudformation with the following changes:
- Added RDS access to PathsAPI
- Changed PathsExpressionTable to RecipesTable
- Updated KeySchema for RecipesTable.

Please check if all changes make sense to you and @ribolzisalvador feel free to merge into master when convenient for you (I'm assuming you're working with the stack). Cheers!

### CODE REVIEW

**Comment by ribolzisalvador** [comment]
Looks fine to me.

Why do we need the VPC on the API?

**Comment by thijs-jung-trv** [comment]
The API needs to be able to access the Paths database to get all paths for a given source so it can test a recipe against these paths.

**Comment by gumuz** [comment]
Looks good! Nice with the !ImportValue's does this work? :)

Merge it you think it's ready!

**Comment by thijs-jung-trv** [comment]
@gumuz I deployed this cloudformation with Roman on Friday and it creates VPC access on the lambda itself. We didn't run any data through it, but from an administrative point of view everything looked good. So it's tested-ish.

**Pull request merged**
