### PR TITLE
Mapper component

### PR DESCRIPTION
**Pull request by gumuz**
For lack of a better name, this will be the mapper component.

It's main 2 purposes are:

* **Extract** values from a path, based on a Recipe

- [x] BooleanExtractor
- [x] NumberExtractor
- [x] YearExtractor
- [x] StringExtractor
- [x] DateExtractor
- [x] TimeExtractor
- [x] CostExtractor

* **Validate** the extracted value based on it's data type.

- [x] BooleanValidator
- [x] NumberValidator
- [x] YearValidator
- [x] StringValidator
- [x] DateValidator
- [x] TimeValidator
- [x] CostValidator

Infra

- [x] Facilities S3 bucket
- [x] Mapper Lambda

### CODE REVIEW

**Comment by gumuz** [comment]
Initial design works like this:

```python
# Simple Recipe placeholder data-class
number_recipe = Recipe(
    source='expedia',
    prefix=['geo', 'location'],
    field=dict(
        facility='location',
        attribute='latitude',
        datatype='number'),
    options=dict(value='latitude: (\d+\.\d+)'))

def test_extractor_number():
    path = ['geo', 'location', 'latitude: 12.345']

    extractor = Extractor(number_recipe)

    assert extractor.extract(path) == dict(
        facility='location',
        attribute='latitude',
        value=Decimal('12.345')
    )
```

**Comment by ribolzisalvador** [comment]
Looks good, do you think it'd be possible to move the recipe from the class constructor to a parameter of the extract() method, as to avoid creating a new instance per class? What are the advantages and disadvantages of either way?

**Comment by gumuz** [comment]
@ribolzisalvador That's not a bad idea actually. The reason why I thought it would be good to do, is so it could re-use the compiled regular expression, but there should be other ways of doing this.

**Comment by ribolzisalvador** [comment]
Oh that's a nice idea, but the compiled expression goes out of scope after calling extract(), maybe make it a static variable? But it's a nice way of re-using the expression, I like the idea.

**Comment by gumuz** [comment]
I've decided to keep it similar to what I had before, because I think the main scenario is that you have a limited set of recipes that you want to test against many paths.

I've refactored it a little bit, but no big changes:

```python
def test_extractor_boolean():
    path = ['facilities', 'spa']

    extractor = Extractor.from_recipe(boolean_recipe)

    assert extractor.parse(path) == dict(
        facility='spa',
        attribute='available',
        value=True
    )
```

**Pull request merged**
